name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: '测试模式'
        required: true
        default: 'basic'
        type: choice
        options:
        - basic
        - full

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run basic tests
      run: |
        python test_setup.py
        
    - name: Install Playwright (if full test)
      if: github.event.inputs.test_mode == 'full'
      run: |
        playwright install chromium
        
    - name: Test scraper import (if full test)
      if: github.event.inputs.test_mode == 'full'
      run: |
        echo "测试模块导入..."
        python -c "import sys; import spotify; print('✅ spotify.py 导入成功')" || echo "❌ spotify.py 导入失败"
        python -c "import sys; import spotify_rate_converter; print('✅ spotify_rate_converter.py 导入成功')" || echo "❌ spotify_rate_converter.py 导入失败"
